language: node_js
node_js:
  - "12.8.0"
cache:
  directories:
  - node_modules
branches:
  only: 
    - dev
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target_branch: master
  on:
    branch: dev
before_script:
  - "npm install -g gatsby-cli"
  - "npm install"
script:
  - "npm run test"
after_success:
  - "npm run build"
