// flow-typed signature: da5138448f74ccb6ac1bb9e40c79abcf
// flow-typed version: <<STUB>>/gatsby-plugin-typegen_v^1.1.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-typegen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-typegen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-typegen/common' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/gatsby-utils' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/plugin-utils' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/types' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/workers/codegen' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/workers' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/workers/insert-types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-typegen/common.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/common'>;
}
declare module 'gatsby-plugin-typegen/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/gatsby-node'>;
}
declare module 'gatsby-plugin-typegen/gatsby-utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/gatsby-utils'>;
}
declare module 'gatsby-plugin-typegen/index' {
  declare module.exports: $Exports<'gatsby-plugin-typegen'>;
}
declare module 'gatsby-plugin-typegen/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen'>;
}
declare module 'gatsby-plugin-typegen/plugin-utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/plugin-utils'>;
}
declare module 'gatsby-plugin-typegen/types.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/types'>;
}
declare module 'gatsby-plugin-typegen/workers/codegen.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/workers/codegen'>;
}
declare module 'gatsby-plugin-typegen/workers/index' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/workers'>;
}
declare module 'gatsby-plugin-typegen/workers/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/workers'>;
}
declare module 'gatsby-plugin-typegen/workers/insert-types.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/workers/insert-types'>;
}
