// flow-typed signature: 6f547b3176a54d74f109060a27cdc758
// flow-typed version: <<STUB>>/react-pdf_v^4.1.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pdf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pdf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pdf/dist/Document' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/DocumentContext' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/entry.jest' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/entry' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/entry.parcel' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/entry.webpack' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/LinkService' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Message' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Outline' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/OutlineContext' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/OutlineItem' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/__tests__/AnnotationLayer' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/__tests__/PageCanvas' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/__tests__/PageSVG' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/__tests__/TextLayer' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/__tests__/TextLayerItem' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/AnnotationLayer' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/PageCanvas' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/PageSVG' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/TextLayer' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Page/TextLayerItem' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/PageContext' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/PasswordResponses' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/pdf.worker.entry' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/Ref' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-pdf/dist/shared/utils' {
  declare module.exports: any;
}

declare module 'react-pdf/src/__tests__/Document' {
  declare module.exports: any;
}

declare module 'react-pdf/src/__tests__/Outline' {
  declare module.exports: any;
}

declare module 'react-pdf/src/__tests__/OutlineItem' {
  declare module.exports: any;
}

declare module 'react-pdf/src/__tests__/Page' {
  declare module.exports: any;
}

declare module 'react-pdf/src/__tests__/Ref' {
  declare module.exports: any;
}

declare module 'react-pdf/src/__tests__/utils' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Document' {
  declare module.exports: any;
}

declare module 'react-pdf/src/DocumentContext' {
  declare module.exports: any;
}

declare module 'react-pdf/src/entry.jest' {
  declare module.exports: any;
}

declare module 'react-pdf/src/entry' {
  declare module.exports: any;
}

declare module 'react-pdf/src/entry.parcel' {
  declare module.exports: any;
}

declare module 'react-pdf/src/entry.webpack' {
  declare module.exports: any;
}

declare module 'react-pdf/src/LinkService' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Message' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Outline' {
  declare module.exports: any;
}

declare module 'react-pdf/src/OutlineContext' {
  declare module.exports: any;
}

declare module 'react-pdf/src/OutlineItem' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/__tests__/AnnotationLayer' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/__tests__/PageCanvas' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/__tests__/PageSVG' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/__tests__/TextLayer' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/__tests__/TextLayerItem' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/AnnotationLayer' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/PageCanvas' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/PageSVG' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/TextLayer' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Page/TextLayerItem' {
  declare module.exports: any;
}

declare module 'react-pdf/src/PageContext' {
  declare module.exports: any;
}

declare module 'react-pdf/src/PasswordResponses' {
  declare module.exports: any;
}

declare module 'react-pdf/src/pdf.worker.entry' {
  declare module.exports: any;
}

declare module 'react-pdf/src/Ref' {
  declare module.exports: any;
}

declare module 'react-pdf/src/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-pdf/src/shared/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pdf/dist/Document.js' {
  declare module.exports: $Exports<'react-pdf/dist/Document'>;
}
declare module 'react-pdf/dist/DocumentContext.js' {
  declare module.exports: $Exports<'react-pdf/dist/DocumentContext'>;
}
declare module 'react-pdf/dist/entry.jest.js' {
  declare module.exports: $Exports<'react-pdf/dist/entry.jest'>;
}
declare module 'react-pdf/dist/entry.js' {
  declare module.exports: $Exports<'react-pdf/dist/entry'>;
}
declare module 'react-pdf/dist/entry.parcel.js' {
  declare module.exports: $Exports<'react-pdf/dist/entry.parcel'>;
}
declare module 'react-pdf/dist/entry.webpack.js' {
  declare module.exports: $Exports<'react-pdf/dist/entry.webpack'>;
}
declare module 'react-pdf/dist/LinkService.js' {
  declare module.exports: $Exports<'react-pdf/dist/LinkService'>;
}
declare module 'react-pdf/dist/Message.js' {
  declare module.exports: $Exports<'react-pdf/dist/Message'>;
}
declare module 'react-pdf/dist/Outline.js' {
  declare module.exports: $Exports<'react-pdf/dist/Outline'>;
}
declare module 'react-pdf/dist/OutlineContext.js' {
  declare module.exports: $Exports<'react-pdf/dist/OutlineContext'>;
}
declare module 'react-pdf/dist/OutlineItem.js' {
  declare module.exports: $Exports<'react-pdf/dist/OutlineItem'>;
}
declare module 'react-pdf/dist/Page.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page'>;
}
declare module 'react-pdf/dist/Page/__tests__/AnnotationLayer.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/__tests__/AnnotationLayer'>;
}
declare module 'react-pdf/dist/Page/__tests__/PageCanvas.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/__tests__/PageCanvas'>;
}
declare module 'react-pdf/dist/Page/__tests__/PageSVG.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/__tests__/PageSVG'>;
}
declare module 'react-pdf/dist/Page/__tests__/TextLayer.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/__tests__/TextLayer'>;
}
declare module 'react-pdf/dist/Page/__tests__/TextLayerItem.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/__tests__/TextLayerItem'>;
}
declare module 'react-pdf/dist/Page/AnnotationLayer.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/AnnotationLayer'>;
}
declare module 'react-pdf/dist/Page/PageCanvas.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/PageCanvas'>;
}
declare module 'react-pdf/dist/Page/PageSVG.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/PageSVG'>;
}
declare module 'react-pdf/dist/Page/TextLayer.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/TextLayer'>;
}
declare module 'react-pdf/dist/Page/TextLayerItem.js' {
  declare module.exports: $Exports<'react-pdf/dist/Page/TextLayerItem'>;
}
declare module 'react-pdf/dist/PageContext.js' {
  declare module.exports: $Exports<'react-pdf/dist/PageContext'>;
}
declare module 'react-pdf/dist/PasswordResponses.js' {
  declare module.exports: $Exports<'react-pdf/dist/PasswordResponses'>;
}
declare module 'react-pdf/dist/pdf.worker.entry.js' {
  declare module.exports: $Exports<'react-pdf/dist/pdf.worker.entry'>;
}
declare module 'react-pdf/dist/Ref.js' {
  declare module.exports: $Exports<'react-pdf/dist/Ref'>;
}
declare module 'react-pdf/dist/shared/propTypes.js' {
  declare module.exports: $Exports<'react-pdf/dist/shared/propTypes'>;
}
declare module 'react-pdf/dist/shared/utils.js' {
  declare module.exports: $Exports<'react-pdf/dist/shared/utils'>;
}
declare module 'react-pdf/src/__tests__/Document.jsx' {
  declare module.exports: $Exports<'react-pdf/src/__tests__/Document'>;
}
declare module 'react-pdf/src/__tests__/Outline.jsx' {
  declare module.exports: $Exports<'react-pdf/src/__tests__/Outline'>;
}
declare module 'react-pdf/src/__tests__/OutlineItem.jsx' {
  declare module.exports: $Exports<'react-pdf/src/__tests__/OutlineItem'>;
}
declare module 'react-pdf/src/__tests__/Page.jsx' {
  declare module.exports: $Exports<'react-pdf/src/__tests__/Page'>;
}
declare module 'react-pdf/src/__tests__/Ref.js' {
  declare module.exports: $Exports<'react-pdf/src/__tests__/Ref'>;
}
declare module 'react-pdf/src/__tests__/utils.js' {
  declare module.exports: $Exports<'react-pdf/src/__tests__/utils'>;
}
declare module 'react-pdf/src/Document.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Document'>;
}
declare module 'react-pdf/src/DocumentContext.jsx' {
  declare module.exports: $Exports<'react-pdf/src/DocumentContext'>;
}
declare module 'react-pdf/src/entry.jest.js' {
  declare module.exports: $Exports<'react-pdf/src/entry.jest'>;
}
declare module 'react-pdf/src/entry.js' {
  declare module.exports: $Exports<'react-pdf/src/entry'>;
}
declare module 'react-pdf/src/entry.parcel.js' {
  declare module.exports: $Exports<'react-pdf/src/entry.parcel'>;
}
declare module 'react-pdf/src/entry.webpack.js' {
  declare module.exports: $Exports<'react-pdf/src/entry.webpack'>;
}
declare module 'react-pdf/src/LinkService.js' {
  declare module.exports: $Exports<'react-pdf/src/LinkService'>;
}
declare module 'react-pdf/src/Message.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Message'>;
}
declare module 'react-pdf/src/Outline.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Outline'>;
}
declare module 'react-pdf/src/OutlineContext.jsx' {
  declare module.exports: $Exports<'react-pdf/src/OutlineContext'>;
}
declare module 'react-pdf/src/OutlineItem.jsx' {
  declare module.exports: $Exports<'react-pdf/src/OutlineItem'>;
}
declare module 'react-pdf/src/Page.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page'>;
}
declare module 'react-pdf/src/Page/__tests__/AnnotationLayer.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/__tests__/AnnotationLayer'>;
}
declare module 'react-pdf/src/Page/__tests__/PageCanvas.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/__tests__/PageCanvas'>;
}
declare module 'react-pdf/src/Page/__tests__/PageSVG.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/__tests__/PageSVG'>;
}
declare module 'react-pdf/src/Page/__tests__/TextLayer.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/__tests__/TextLayer'>;
}
declare module 'react-pdf/src/Page/__tests__/TextLayerItem.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/__tests__/TextLayerItem'>;
}
declare module 'react-pdf/src/Page/AnnotationLayer.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/AnnotationLayer'>;
}
declare module 'react-pdf/src/Page/PageCanvas.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/PageCanvas'>;
}
declare module 'react-pdf/src/Page/PageSVG.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/PageSVG'>;
}
declare module 'react-pdf/src/Page/TextLayer.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/TextLayer'>;
}
declare module 'react-pdf/src/Page/TextLayerItem.jsx' {
  declare module.exports: $Exports<'react-pdf/src/Page/TextLayerItem'>;
}
declare module 'react-pdf/src/PageContext.jsx' {
  declare module.exports: $Exports<'react-pdf/src/PageContext'>;
}
declare module 'react-pdf/src/PasswordResponses.js' {
  declare module.exports: $Exports<'react-pdf/src/PasswordResponses'>;
}
declare module 'react-pdf/src/pdf.worker.entry.js' {
  declare module.exports: $Exports<'react-pdf/src/pdf.worker.entry'>;
}
declare module 'react-pdf/src/Ref.js' {
  declare module.exports: $Exports<'react-pdf/src/Ref'>;
}
declare module 'react-pdf/src/shared/propTypes.js' {
  declare module.exports: $Exports<'react-pdf/src/shared/propTypes'>;
}
declare module 'react-pdf/src/shared/utils.js' {
  declare module.exports: $Exports<'react-pdf/src/shared/utils'>;
}
