// flow-typed signature: 1f914fd94e2af08b703f3f801949b5f4
// flow-typed version: <<STUB>>/smooth-scroll_v^16.1.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smooth-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smooth-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smooth-scroll/dist/smooth-scroll' {
  declare module.exports: any;
}

declare module 'smooth-scroll/dist/smooth-scroll.min' {
  declare module.exports: any;
}

declare module 'smooth-scroll/dist/smooth-scroll.polyfills' {
  declare module.exports: any;
}

declare module 'smooth-scroll/dist/smooth-scroll.polyfills.min' {
  declare module.exports: any;
}

declare module 'smooth-scroll/gulpfile' {
  declare module.exports: any;
}

declare module 'smooth-scroll/src/js/smooth-scroll/_closest.polyfill' {
  declare module.exports: any;
}

declare module 'smooth-scroll/src/js/smooth-scroll/_customEvent.polyfill' {
  declare module.exports: any;
}

declare module 'smooth-scroll/src/js/smooth-scroll/_requestAnimationFrame.polyfill' {
  declare module.exports: any;
}

declare module 'smooth-scroll/src/js/smooth-scroll/smooth-scroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smooth-scroll/dist/smooth-scroll.js' {
  declare module.exports: $Exports<'smooth-scroll/dist/smooth-scroll'>;
}
declare module 'smooth-scroll/dist/smooth-scroll.min.js' {
  declare module.exports: $Exports<'smooth-scroll/dist/smooth-scroll.min'>;
}
declare module 'smooth-scroll/dist/smooth-scroll.polyfills.js' {
  declare module.exports: $Exports<'smooth-scroll/dist/smooth-scroll.polyfills'>;
}
declare module 'smooth-scroll/dist/smooth-scroll.polyfills.min.js' {
  declare module.exports: $Exports<'smooth-scroll/dist/smooth-scroll.polyfills.min'>;
}
declare module 'smooth-scroll/gulpfile.js' {
  declare module.exports: $Exports<'smooth-scroll/gulpfile'>;
}
declare module 'smooth-scroll/src/js/smooth-scroll/_closest.polyfill.js' {
  declare module.exports: $Exports<'smooth-scroll/src/js/smooth-scroll/_closest.polyfill'>;
}
declare module 'smooth-scroll/src/js/smooth-scroll/_customEvent.polyfill.js' {
  declare module.exports: $Exports<'smooth-scroll/src/js/smooth-scroll/_customEvent.polyfill'>;
}
declare module 'smooth-scroll/src/js/smooth-scroll/_requestAnimationFrame.polyfill.js' {
  declare module.exports: $Exports<'smooth-scroll/src/js/smooth-scroll/_requestAnimationFrame.polyfill'>;
}
declare module 'smooth-scroll/src/js/smooth-scroll/smooth-scroll.js' {
  declare module.exports: $Exports<'smooth-scroll/src/js/smooth-scroll/smooth-scroll'>;
}
