// flow-typed signature: 68602e716cca71dfcb7f32e355d63a17
// flow-typed version: <<STUB>>/stylelint-config-recommended_v^3.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-recommended'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-recommended' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-recommended/index' {
  declare module.exports: $Exports<'stylelint-config-recommended'>;
}
declare module 'stylelint-config-recommended/index.js' {
  declare module.exports: $Exports<'stylelint-config-recommended'>;
}
